source 'https://rubygems.org'
gem 'rails', '~> 5.1'
gem 'mysql2'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'haml'
gem 'nifty-utils'
gem 'nilify_blanks'
gem 'authie'
gem 'kaminari'
gem 'chronic'
gem 'dynamic_form'
gem 'activevalidators'
gem 'bcrypt'
gem 'rails_env_config'
gem 'chronic_duration'
gem 'datey'
gem 'nifty-attachments'
gem 'puma'
<<<<<<< HEAD
gem 'moonrope'
gem 'florrick'
gem 'delayed_job_active_record'
gem 'foreman'
gem 'redcarpet'
gem 'premailer'
gem 'rack-custom-proxies'
gem 'log_logins'
=======
#gem 'passenger'
gem 'moonrope', '~> 1.3'
gem 'florrick', '~> 1.1'
gem 'delayed_job_active_record'
gem 'foreman'
gem 'redcarpet', '~> 3.2.2'
gem 'premailer', '~> 1.8.3'
gem 'therubyracer'
gem "daemons"
>>>>>>> stable

group :development, :test do
  gem 'annotate', '~> 2.6.5'
end
