# Staytus environment configuration. Staytus uses
# unix environment variables to provide its configuration.
# If your hosting environment does not support setting this
# easily, you can add them to config/environment.yml and
# they will be loaded when the application starts.

# The theme to use
STAYTUS_THEME: 'default'

# If enabled, the application will allow any username/password
# combination to login to the admin area.
STAYTUS_DEMO: '0'

# Configure an SMTP server for sending messages. If you don't
# configure an SMTP service, e-mail will be sent using sendmail.
STAYTUS_SMTP_HOSTNAME: smtp.deliverhq.com
STAYTUS_SMTP_PORT: '25'
STAYTUS_SMTP_USERNAME: your-username
STAYTUS_SMTP_PASSWORD: your-password

# Configure the email lists for Minor, Major, and Critical issue emails
MINOR_EMAIL_LIST: 'minor@example.com'
MAJOR_EMAIL_LIST: 'minor@example.com'
CRITICAL_EMAIL_LIST: 'minor@example.com'

# Configure the email lists for Low Risk, Medium Risk, and High Risk planned maintnence
LOW_RISK_EMAI: 'low_risk@example.com'
MEDIUM_RISK_EMAIL: 'medium_risk@example.com'
HIGH_RISK_EMAIL: 'high_risk@example.com'
